version: '3.8'

services:

  postgres_db:
    image: postgres:16-alpine
    container_name: toolweight_postgres_db
    
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    
    ports:
      - "5432:5432"
      
    volumes:
      - toolweight_db_data:/var/lib/postgresql/data
      
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: supersecretpassword
    
    depends_on:
      - postgres_db
    
    ports:
      - "8888:80"
    
    volumes:
      - toolweight_pgadmin_data:/var/lib/pgadmin
      
    restart: always

volumes:
  toolweight_db_data:
    driver: local
  toolweight_pgadmin_data:
    driver: local